services:

  laravel-docker:
    container_name: issste
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: issste
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1